language: c

sudo: false

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
      os: linux
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
      os: linux
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
      os: linux
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
      os: linux
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"
      os: linux
    # - compiler: ": Lua51-osx"
    #   env: LUA="lua 5.1"
    #   os: osx

services:
  - redis-server

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - export CC=gcc
  - gcc --version
  - redis-cli --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:~/Library/Python/2.7/bin/; fi
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate
  - luarocks show lluv > /dev/null 2>&1 || bash .travis/setup_uv.sh

install:
  - luarocks show lluv > /dev/null 2>&1 || luarocks install lluv UV_DIR=$TRAVIS_BUILD_DIR/libuv
  - luarocks make rockspecs/lluv-redis-scm-0.rockspec 

before_script:
  - luarocks show lua_cliargs      > /dev/null 2>&1 || luarocks install lua_cliargs 2.5
  - luarocks show stacktraceplus   > /dev/null 2>&1 || luarocks install stacktraceplus
  - luarocks show lua-curl         > /dev/null 2>&1 || luarocks install lua-curl
  - luarocks show luacov-coveralls > /dev/null 2>&1 || luarocks install luacov-coveralls
  - luarocks show lunitx           > /dev/null 2>&1 || luarocks install lunitx
  - luarocks show lluv-busted      > /dev/null 2>&1 || luarocks install lluv-busted --server=http://luarocks.org/dev

script: 
  - cd test
  - lunit.sh test_stream.lua
  - lunit.sh test_commander.lua
  - lunit.sh test_redis.lua
  - lua      test_redis_pub_sub.lua
  - lua      test_connect.lua
  - busted_bootstrap --verbose --coverage test.busted
  - busted_bootstrap --verbose --coverage test_reconnect.busted

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
