language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    # - LUA=lua5.2
    # - LUA=lua5.3
    # - LUA=luajit

branches:
  only:
    - master

services:
  - redis-server

before_install:
  - source .travis/setenv_lua.sh
  - bash .travis/setup_uv.sh
  - luarocks install luacov-coveralls
  - luarocks install lunitx
  - luarocks install lluv --server=http://rocks.moonscript.org/dev UV_DIR=$TRAVIS_BUILD_DIR/libuv

install:
  - luarocks make rockspecs/lluv-redis-scm-0.rockspec 

script: 
  - cd test
  - lunit.sh test_stream.lua
  - lunit.sh test_commander.lua
  - lunit.sh test_redis.lua
  - lua      test_redis_pub_sub.lua
  - lua      test_connect.lua
  - redis-cli --version
  - redis-cli eval "redis.call('set', 'a', math.huge) local a=redis.call('get', 'a') return {a, math.huge}" 0

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
